### ISSUE TITLE
Problem with hash size

### ISSUE THREAD

**Issue by SzotsGabor** [Mathmagician8191/Liberty-Chess#2]
Hi Matthew,

The engine outputs this: option name Hash type spin default 64 min 0 max 4294967296

I don't understand that big number. What is more, the engine does not accept values over 64.

PS. I am running a tournament. Unfortunately your assessment of 2300 seems exaggerated, my first results indicate it will be below 2100.

Gabor Szots
CCRL

**Comment by Mathmagician8191** [comment]
What exactly happens when you try to give it a value over 64 (it works fine for me on linux, so this might be a windows specific issue)?

Do you have a log of uci commands sent/receieved?

**Comment by SzotsGabor** [comment]
Under Arena the default hash value of 64 MB is used. Under Cute Chess GUI as soon as I clicked on the hashvalue it changed to 0 and could not be modified any more.
Maybe later I'll provide an Arena debug but I have no time at the moment.

**Comment by Mathmagician8191** [comment]
It looks like the large maximum value for hash breaks cutechess, if I lower the maximum value a bit it does work.
I will update the builds to fix that issue.

**Comment by Mathmagician8191** [comment]
I've updated the builds, the new builds should no longer have the issue

**Comment by SzotsGabor** [comment]
option name Hash type spin default 64 min 0 max 268435456

Although the problem has gone I still can't interpret that big number.

**Comment by Mathmagician8191** [comment]
The number is 2 ^ 28, it means that the maximum amount of hash supported is 256 TB

**Comment by SzotsGabor** [comment]
> The number is 2 ^ 28, it means that the maximum amount of hash supported is 256 TB

OK, I haven't seen values greater than 2048 yet. And 256 TB is almost  1000 times as much as my 32 GB total memory, I did not know there are so big machines.

**Comment by Mathmagician8191** [comment]
I don't know if any machines have that much ram yet either but I wanted to make sure it was future proof
